import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function readSource(relativePath) {
  try {
    return await readFile(new URL(relativePath, import.meta.url), "utf8");
  } catch {
    return null;
  }
}

const mirrors = [
  ["../src/components/awful-cases-core.js", "../public/pets/awful-cases/awful-cases-core.js"],
  ["../src/components/awful-cases-content.js", "../public/pets/awful-cases/awful-cases-content.js"],
  ["../src/components/awful-cases-runtime.js", "../public/pets/awful-cases/awful-cases.js"],
];

test("Awful Cases public modules are generated byte-for-byte from canonical source", async () => {
  for (const [sourcePath, publicPath] of mirrors) {
    const source = await readSource(sourcePath);
    const mirror = await readSource(publicPath);
    assert.ok(source, `missing canonical source: ${sourcePath}`);
    assert.ok(mirror, `missing generated mirror: ${publicPath}`);
    assert.equal(mirror, source, publicPath);
  }
});

test("embedded Awful Cases is a thin Russian mount around the canonical runtime", async () => {
  const source = await readSource("../src/components/awful-cases-game.js");
  assert.ok(source);
  assert.match(source, /import \{ enhanceAwfulCases \} from "\.\/awful-cases-runtime\.js"/);
  assert.match(source, /locale:\s*"ru"/);
  assert.doesNotMatch(source, /function drawTask/);
  assert.doesNotMatch(source, /data:image\//);
});

test("canonical runtime owns lifecycle and consumes the pure core", async () => {
  const source = await readSource("../src/components/awful-cases-runtime.js");
  assert.ok(source, "canonical Awful Cases runtime must exist");
  assert.match(source, /from "\.\/awful-cases-core\.js"/);
  assert.match(source, /from "\.\/awful-cases-content\.js"/);
  assert.match(source, /SESSION_PLAN/);
  assert.match(source, /actionFromCode/);
  assert.match(source, /recordCorrect/);
  assert.match(source, /recordMistake/);
  assert.match(source, /missIsLethal/);
  assert.match(source, /AbortController/);
  assert.match(source, /ResizeObserver/);
  assert.match(source, /destroy\(\)/);
  assert.match(source, /Number\.isFinite\(game\.time\)/);
  assert.match(source, /const frame = RUN\[frameIndex\] \?\? RUN\[0\]/);
  assert.doesNotMatch(source, /Key[WSAD]/);
});

test("both game surfaces expose onboarding, guidance and all six actions", async () => {
  const [component, standalone] = await Promise.all([
    readSource("../src/components/specialized/awful-cases-game.ts"),
    readSource("../public/pets/awful-cases/index.html"),
  ]);

  for (const source of [component, standalone]) {
    assert.ok(source);
    assert.match(source, /data-awful-cases/);
    assert.match(source, /data-awful-cases-canvas/);
    assert.match(source, /data-awful-cases-onboarding/);
    assert.match(source, /data-awful-cases-onboarding-actions/);
    assert.match(source, /data-awful-cases-prompt/);
    assert.match(source, /data-awful-cases-controls/);
    for (const action of ["upper", "lower", "title", "toggle", "lint", "sentence"]) {
      assert.match(source, new RegExp(`data-awful-cases-action="${action}"`));
    }
    assert.doesNotMatch(source, />[WSAD]<\/b>/);
    assert.doesNotMatch(source, /WASD/);
  }

  assert.match(component, /data-awful-cases-action="upper"[\s\S]*?<b>↑<\/b>/);
  assert.match(component, /data-awful-cases-action="lower"[\s\S]*?<b>↓<\/b>/);
  assert.match(component, /data-awful-cases-action="title"[\s\S]*?<b>←<\/b>/);
  assert.match(component, /data-awful-cases-action="toggle"[\s\S]*?<b>→<\/b>/);
  assert.match(standalone, /data-awful-cases-action="upper"[\s\S]*?<b>↑<\/b>/);
  assert.match(standalone, /data-awful-cases-action="lower"[\s\S]*?<b>↓<\/b>/);
  assert.match(standalone, /data-awful-cases-action="title"[\s\S]*?<b>←<\/b>/);
  assert.match(standalone, /data-awful-cases-action="toggle"[\s\S]*?<b>→<\/b>/);
});

test("trainer styling keeps mobile geometry, guidance and reduced-motion support", async () => {
  const [componentStyles, standaloneStyles] = await Promise.all([
    readSource("../src/styles/components.css"),
    readSource("../public/pets/awful-cases/awful-cases.css"),
  ]);
  assert.ok(componentStyles);
  assert.ok(standaloneStyles);

  assert.match(componentStyles, /\.awful-cases-game \.start\{[^}]*text-align:center/);
  assert.match(componentStyles, /\.awful-cases-game \.runner-controls__prompt/);
  assert.match(componentStyles, /aspect-ratio:\s*1\s*\/\s*1/);
  assert.match(
    componentStyles,
    /@media \(hover: hover\) and \(pointer: fine\)[\s\S]*?\.awful-cases-game \.runner-controls[\s\S]*?display:\s*none/,
  );

  assert.match(standaloneStyles, /\.awful-cases \.start\{[^}]*text-align:center/);
  assert.match(standaloneStyles, /\.awful-cases \.runner-controls__prompt/);
  assert.match(
    standaloneStyles,
    /@media \(prefers-reduced-motion: reduce\)[\s\S]*?animation:\s*none/,
  );
  assert.ok(
    standaloneStyles.lastIndexOf("@media (hover:hover) and (pointer:fine)") >
      standaloneStyles.lastIndexOf(".runner-controls:not([hidden])"),
    "standalone fine-pointer hiding must win the cascade after the visible-controls rule",
  );
});

test("Awful Cases sync tool owns public runtime mirrors", async () => {
  const generator = await readSource("../tools/generate-awful-cases-runtime.mjs");
  const pkgSource = await readSource("../package.json");
  assert.ok(generator, "Awful Cases mirror generator must exist");
  assert.ok(pkgSource);
  const pkg = JSON.parse(pkgSource);
  assert.equal(pkg.scripts["awful-cases:sync"], "node tools/generate-awful-cases-runtime.mjs");
  assert.equal(pkg.scripts["awful-cases:check"], "node tools/generate-awful-cases-runtime.mjs --check");
  assert.match(generator, /awful-cases-core\.js/);
  assert.match(generator, /awful-cases-content\.js/);
  assert.match(generator, /awful-cases-runtime\.js/);
});

test("browser playtest uses the real default keys and is wired as a package script", async () => {
  const playtest = await readSource("../tools/e2e/playtest-awful-cases.mjs");
  const pkgSource = await readSource("../package.json");
  assert.ok(playtest, "Awful Cases browser playtest must exist");
  assert.ok(pkgSource);
  const pkg = JSON.parse(pkgSource);
  assert.equal(
    pkg.scripts["awful-cases:playtest"],
    "npm run build:vite && node tools/e2e/playtest-awful-cases.mjs",
  );
  for (const [action, code] of [
    ["upper", "ArrowUp"],
    ["lower", "ArrowDown"],
    ["title", "ArrowLeft"],
    ["toggle", "ArrowRight"],
    ["lint", "PageDown"],
    ["sentence", "Delete"],
  ]) {
    assert.match(playtest, new RegExp(action + ':\\s*"' + code + '"'));
  }
  assert.doesNotMatch(playtest, /upper:\s*"w"|lower:\s*"s"|title:\s*"a"|toggle:\s*"d"/i);
});

test("trainer hardening respects motion preference and exposes command-button semantics", async () => {
  const runtime = await readSource("../src/components/awful-cases-runtime.js");
  assert.ok(runtime);
  assert.match(runtime, /matchMedia[\s\S]*?prefers-reduced-motion: reduce/);
  assert.match(runtime, /reducedMotion/);
  assert.doesNotMatch(runtime, /aria-pressed/);
});

test("embedded trainer keeps one game focus target with visible focus states", async () => {
  const [component, styles] = await Promise.all([
    readSource("../src/components/specialized/awful-cases-game.ts"),
    readSource("../src/styles/components.css"),
  ]);
  assert.ok(component);
  assert.ok(styles);
  assert.doesNotMatch(component, /data-awful-cases[^>]*tabindex="0"[^>]*><canvas/);
  assert.match(component, /data-awful-cases-canvas[^>]*tabindex="0"/);
  assert.match(styles, /\.awful-cases-game \.restart__button:focus-visible/);
  assert.match(styles, /\.awful-cases-game \.runner-controls button:focus-visible/);
});

test("touch control labels remain readable on both trainer surfaces", async () => {
  const [componentStyles, standaloneStyles] = await Promise.all([
    readSource("../src/styles/components.css"),
    readSource("../public/pets/awful-cases/awful-cases.css"),
  ]);
  assert.ok(componentStyles);
  assert.ok(standaloneStyles);
  assert.doesNotMatch(componentStyles, /\.awful-cases-game \.runner-controls span\{font-size:6px/);
  assert.doesNotMatch(standaloneStyles, /\.awful-cases \.runner-controls span\{font-size:6px/);
});

