import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function readSource(relativePath) {
  return readFile(new URL(relativePath, import.meta.url), "utf8");
}

const mirrors = [
  ["../src/components/awful-cases-core.js", "../public/pets/awful-cases/awful-cases-core.js"],
  ["../src/components/awful-cases-content.js", "../public/pets/awful-cases/awful-cases-content.js"],
  ["../src/components/awful-cases-runtime.js", "../public/pets/awful-cases/awful-cases.js"],
];

test("Awful Cases public modules are generated byte-for-byte from canonical source", async () => {
  for (const [sourcePath, publicPath] of mirrors) {
    assert.equal(await readSource(publicPath), await readSource(sourcePath), publicPath);
  }
});

test("embedded Awful Cases is a thin Russian mount around the canonical runtime", async () => {
  const source = await readSource("../src/components/awful-cases-game.js");
  assert.match(source, /import \{ enhanceAwfulCases \} from "\.\/awful-cases-runtime\.js"/);
  assert.match(source, /locale:\s*"ru"/);
  assert.doesNotMatch(source, /data:image\//);
  assert.doesNotMatch(source, /function drawTask/);
});

test("canonical runtime consumes the pure game core", async () => {
  const source = await readSource("../src/components/awful-cases-runtime.js");
  assert.match(source, /from "\.\/awful-cases-core\.js"/);
  assert.match(source, /SESSION_PLAN/);
  assert.match(source, /actionFromCode/);
  assert.match(source, /recordCorrect/);
  assert.match(source, /recordMistake/);
  assert.match(source, /missIsLethal/);
  assert.match(source, /Number\.isFinite\(game\.time\)/);
  assert.match(source, /const frame = RUN\[frameIndex\] \?\? RUN\[0\]/);
});

test("embedded game exposes the shared root and control hooks", async () => {
  const source = await readSource("../src/components/specialized/awful-cases-game.ts");
  assert.match(source, /data-awful-cases/);
  assert.match(source, /data-awful-cases-canvas/);
  assert.match(source, /data-awful-cases-start-button/);
  assert.match(source, /data-awful-cases-restart-button/);
  assert.match(source, /data-runner-action="lint"/);
  assert.match(source, /data-runner-action="sentence"/);
});

test("Awful Cases keeps responsive mobile geometry and fine-pointer control hiding", async () => {
  const source = await readSource("../src/styles/components.css");
  assert.match(source, /&\[data-device="browser"\] \.mockup__viewport \{\s*aspect-ratio: 1 \/ 1;/);
  assert.match(
    source,
    /@media \(hover: hover\) and \(pointer: fine\) \{[\s\S]*?\.awful-cases-game \.runner-controls \{\s*display: none;/,
  );
});

test("standalone Awful Cases exposes all six touch actions", async () => {
  const source = await readSource("../public/pets/awful-cases/index.html");
  assert.match(source, /data-awful-cases-controls/);
  for (const action of ["upper", "lower", "title", "toggle", "lint", "sentence"]) {
    assert.match(source, new RegExp(`data-awful-cases-action="${action}"`));
  }
});
