export const MOUNTS = [
  {
    id: "petProjectFrames",
    phase: "content",
    selector: "[data-pet-project-frame]",
    load: () => import("../visuals/dom/pet-project-frames.js"),
    mount: (module, root) => module.mountPetProjectFrames(root),
  },
  {
    id: "gsap",
    phase: "critical",
    load: () => import("../vendor/gsap-globals.js"),
  },
  {
    id: "jesteiBentoBrandLogo",
    phase: "critical",
    selector: "#jestei-results .jestei-bento__logo-inspector:not(.jestei-bento__rebrand-equation)",
    load: () => import("../visuals/dom/jestei-bento-brand-logo.js"),
    mount: (module, root) => module.mountJesteiBentoBrandLogo(root),
  },
  {
    id: "components",
    phase: "content",
    selector: "#main",
    load: () => import("../components/index.js"),
    mount: (module, root) => module.initComponents(root),
  },
  {
    id: "hideJesteiLandings",
    phase: "content",
    selector: "#jestei-landings",
    load: () => import("./hide-jestei-landings.js"),
    mount: (module, root) => module.mountHiddenJesteiLandings(root),
  },
  {
    id: "jesteiProcessScene",
    phase: "visual",
    selector: "#jestei-results .jestei-bento__card--manual",
    load: () => import("../visuals/dom/jestei-process-scene-live.js"),
    mount: (module, root) => module.mountJesteiProcessScene(root),
  },
  {
    id: "jesteiUsaGlobe",
    phase: "visual",
    selector: "#jestei-usa-globe",
    load: () => import("../visuals/dom/jestei-usa-globe.js"),
    mount: (module, root) => module.mountJesteiUsaGlobe(root),
  },
  {
    id: "jesteiProcessLayout",
    phase: "afterPaint",
    selector: "#jestei-results .jestei-bento__card--manual",
    load: () => import("../visuals/dom/jestei-process-layout.js"),
    mount: (module, root) => module.mountJesteiProcessLayout(root),
  },
  {
    id: "mediaMarquee",
    phase: "near",
    selector: "[data-media-marquee], .section-media-marquee, .jestei-policy-marquee",
    load: () => import("../visuals/dom/media-marquee.js"),
  },
  {
    id: "archiveMediaScenes",
    phase: "near",
    selector: "[data-archive-media-scene]",
    rootMargin: "1000px 0px",
    load: () => import("../visuals/dom/archive-media-scenes.js"),
    mount: (module, root) => module.initArchiveMediaScenes(root),
  },
  {
    id: "policyBook",
    phase: "content",
    selector: "[data-policy-book], .policy-book",
    load: () => import("../visuals/dom/policy-book.js"),
  },
  {
    id: "listScroll",
    phase: "content",
    selector: ".list-scroll-x, .jestei-action-rail__viewport",
    load: () => import("../visuals/dom/list-scroll.js"),
  },
  {
    id: "portfolioGallery",
    phase: "content",
    selector: "[data-lightbox-item], [data-lightbox-video]",
    load: () => import("../visuals/dom/portfolio-gallery.js"),
    mount: (module, root) => module.initPortfolioGallery(root),
  },
  {
    id: "jesteiActionRail",
    phase: "content",
    selector: "[data-jestei-action-rail]",
    load: () => import("../visuals/dom/jestei-action-rail.js"),
    mount: (module, root) => module.initJesteiActionRail(root),
  },
  {
    id: "artifactReader",
    phase: "content",
    selector: "[data-artifact-reader], [data-artifact-reader-open], .artifact-reader, .artifact-stage",
    load: () => import("../visuals/dom/artifact-reader.js"),
    mount: (module, root) => module.initArtifactReaders(root),
  },
  {
    id: "showcaseSignatures",
    phase: "content",
    selector: "[data-color-headline], [data-showcase-signature], .showcase-signature",
    load: () => import("../components/showcase-signatures.js"),
    mount: (module, root) => module.initShowcaseSignatures(root),
  },
  {
    id: "artifactFullscreen",
    phase: "content",
    selector: "[data-policy-book], [data-artifact-fullscreen], [data-artifact-fullscreen-open]",
    load: () => import("../components/artifact-fullscreen.js"),
    mount: (module, root) => module.initArtifactFullscreen(root),
  },
  {
    id: "mediaSlider",
    phase: "near",
    selector: "[data-showcase-auto-slider]",
    rootMargin: "1000px 0px",
    load: () => import("../visuals/dom/media-slider.js"),
    mount: (module, root) => module.initMediaSliders(root),
  },
  {
    id: "playlistFilter",
    phase: "near",
    selector: "[data-playlist-filter-embed], [data-playlist-filter], .playlist-filter-embed, .playlist-filter",
    rootMargin: "1200px 0px",
    load: () => import("../visuals/dom/playlist-filter-embed.js"),
    mount: (module, root) => module.initPlaylistFilterEmbed(root),
  },
  {
    id: "proximity",
    phase: "idle",
    selector: "[data-proximity], [data-proximity-target], [data-proximity-root], .proximity-button, .proximity-card",
    load: () => import("../components/proximity-components.js"),
  },
];
