import { mountMasonry, MASONRY_DEFAULTS } from "./index.js";
import {
  mountDataComponent,
  MASONRY_PRESETS,
  buildInteraction,
  createSharedFields,
  makeField,
  scaledNumberList,
  scaledSpeed,
} from "../../runtime/master-runtime.js";

const PRESET_ORDER = [
  "scroll-driven",
  "autoplay",
  "scroll-slowdown",
  "columns-ltr-active-slow",
  "columns-ltr-active-fast",
  "columns-rtl-active-slow",
  "columns-rtl-active-fast",
  "center-slowdown",
];

export const MASONRY_FIELDS = [
  ...createSharedFields({
    presetOptions: PRESET_ORDER,
    defaultPreset: "autoplay",
    cycleMs: 14000,
  }),
  makeField({
    name: "animationDirection",
    attr: "data-animation-direction",
    defaultValue: MASONRY_DEFAULTS.direction,
    group: "motion",
    label: "direction",
    control: "select",
    options: ["up", "down"],
  }),
  makeField({
    name: "animationSpeed",
    attr: "data-animation-speed",
    defaultValue: MASONRY_DEFAULTS.speed,
    parse: "number",
    group: "motion",
    label: "base speed",
    control: "number",
    min: 0,
    max: 2,
    step: 0.001,
  }),
  makeField({
    name: "animationColumnSpeeds",
    attr: "data-animation-column-speeds",
    defaultValue: MASONRY_DEFAULTS.columnSpeeds,
    parse: "numberList",
    group: "motion",
    label: "column speeds",
    control: "text",
  }),
  makeField({
    name: "animationPausedColumns",
    attr: "data-animation-paused-columns",
    defaultValue: "",
    parse: "integerList",
    group: "motion",
    label: "paused columns",
    control: "text",
  }),
  makeField({
    name: "animationColumnCount",
    attr: "data-animation-column-count",
    defaultValue: MASONRY_DEFAULTS.columnCount,
    parse: "autoInteger",
    group: "columns",
    label: "column count: auto or number",
    control: "text",
  }),
  makeField({
    name: "animationPreferredColumnWidth",
    attr: "data-animation-preferred-column-width",
    defaultValue: MASONRY_DEFAULTS.preferredColumnWidth,
    parse: "number",
    group: "columns",
    label: "preferred width",
    control: "range",
    min: 48,
    max: 480,
    step: 1,
  }),
  makeField({
    name: "animationMinColumnWidth",
    attr: "data-animation-min-column-width",
    defaultValue: MASONRY_DEFAULTS.minColumnWidth,
    parse: "number",
    group: "columns",
    label: "min width",
    control: "range",
    min: 24,
    max: 320,
    step: 1,
  }),
  makeField({
    name: "animationMaxColumnWidth",
    attr: "data-animation-max-column-width",
    defaultValue: MASONRY_DEFAULTS.maxColumnWidth,
    parse: "number",
    group: "columns",
    label: "max width",
    control: "range",
    min: 48,
    max: 640,
    step: 1,
  }),
  makeField({
    name: "animationMaxColumnCount",
    attr: "data-animation-max-column-count",
    defaultValue: MASONRY_DEFAULTS.maxColumnCount,
    parse: "integer",
    group: "columns",
    label: "max columns",
    control: "range",
    min: 1,
    max: 24,
    step: 1,
  }),
  makeField({
    name: "animationColumnWeights",
    attr: "data-animation-column-weights",
    defaultValue: "",
    parse: "numberList",
    group: "columns",
    label: "column weights",
    control: "text",
  }),
  makeField({
    name: "animationGap",
    attr: "data-animation-gap",
    defaultValue: MASONRY_DEFAULTS.gap,
    parse: "number",
    group: "geometry",
    label: "gap",
    control: "range",
    min: 0,
    max: 64,
    step: 1,
  }),
  makeField({
    name: "animationColumnGap",
    attr: "data-animation-column-gap",
    defaultValue: "",
    parse: "nullableNumber",
    group: "geometry",
    label: "column gap, blank = gap",
    control: "text",
  }),
  makeField({
    name: "animationRowGap",
    attr: "data-animation-row-gap",
    defaultValue: "",
    parse: "nullableNumber",
    group: "geometry",
    label: "row gap, blank = gap",
    control: "text",
  }),
  makeField({
    name: "animationRadius",
    attr: "data-animation-radius",
    defaultValue: MASONRY_DEFAULTS.radius,
    parse: "number",
    group: "geometry",
    label: "card radius",
    control: "range",
    min: 0,
    max: 64,
    step: 1,
  }),
  makeField({
    name: "animationPadding",
    attr: "data-animation-padding",
    defaultValue: MASONRY_DEFAULTS.padding,
    parse: "number",
    group: "geometry",
    label: "padding",
    control: "range",
    min: 0,
    max: 160,
    step: 1,
  }),
  makeField({
    name: "animationFadeEnabled",
    attr: "data-animation-fade-enabled",
    defaultValue: MASONRY_DEFAULTS.fade.enabled,
    parse: "boolean",
    group: "fade",
    label: "fade",
    control: "checkbox",
  }),
  makeField({
    name: "animationFadeSize",
    attr: "data-animation-fade-size",
    defaultValue: MASONRY_DEFAULTS.fade.size,
    parse: "number",
    group: "fade",
    label: "fade size",
    control: "range",
    min: 0,
    max: 0.49,
    step: 0.01,
    visibleWhen: { animationFadeEnabled: true },
  }),
  makeField({
    name: "animationFadeTopSize",
    attr: "data-animation-fade-top-size",
    defaultValue: "",
    parse: "nullableNumber",
    group: "fade",
    label: "top size, blank = fade size",
    control: "text",
    visibleWhen: { animationFadeEnabled: true },
  }),
  makeField({
    name: "animationFadeBottomSize",
    attr: "data-animation-fade-bottom-size",
    defaultValue: "",
    parse: "nullableNumber",
    group: "fade",
    label: "bottom size, blank = fade size",
    control: "text",
    visibleWhen: { animationFadeEnabled: true },
  }),
  makeField({
    name: "animationFadeTop",
    attr: "data-animation-fade-top",
    defaultValue: MASONRY_DEFAULTS.fade.sides.top,
    parse: "boolean",
    group: "fade",
    label: "fade top",
    control: "checkbox",
    visibleWhen: { animationFadeEnabled: true },
  }),
  makeField({
    name: "animationFadeBottom",
    attr: "data-animation-fade-bottom",
    defaultValue: MASONRY_DEFAULTS.fade.sides.bottom,
    parse: "boolean",
    group: "fade",
    label: "fade bottom",
    control: "checkbox",
    visibleWhen: { animationFadeEnabled: true },
  }),
  makeField({
    name: "animationPreload",
    attr: "data-animation-preload",
    defaultValue: MASONRY_DEFAULTS.preload,
    parse: "number",
    group: "layout",
    label: "preload",
    control: "range",
    min: 0,
    max: 1200,
    step: 10,
  }),
  makeField({
    name: "animationMinCycleRatio",
    attr: "data-animation-min-cycle-ratio",
    defaultValue: MASONRY_DEFAULTS.minCycleRatio,
    parse: "number",
    group: "layout",
    label: "min cycle ratio",
    control: "range",
    min: 1,
    max: 8,
    step: 0.05,
  }),
  makeField({
    name: "animationMaxClonePasses",
    attr: "data-animation-max-clone-passes",
    defaultValue: MASONRY_DEFAULTS.maxClonePasses,
    parse: "integer",
    group: "layout",
    label: "max clone passes",
    control: "range",
    min: 1,
    max: 64,
    step: 1,
  }),
  makeField({
    name: "animationMinTileHeight",
    attr: "data-animation-min-tile-height",
    defaultValue: MASONRY_DEFAULTS.minTileHeight,
    parse: "number",
    group: "tiles",
    label: "min tile height",
    control: "range",
    min: 24,
    max: 400,
    step: 1,
  }),
  makeField({
    name: "animationMaxTileHeight",
    attr: "data-animation-max-tile-height",
    defaultValue: MASONRY_DEFAULTS.maxTileHeight,
    parse: "number",
    group: "tiles",
    label: "max tile height",
    control: "range",
    min: 100,
    max: 1200,
    step: 5,
  }),
  makeField({
    name: "animationMinLandscapeScale",
    attr: "data-animation-min-landscape-scale",
    defaultValue: MASONRY_DEFAULTS.minLandscapeScale,
    parse: "number",
    group: "tiles",
    label: "min landscape scale",
    control: "range",
    min: 0.1,
    max: 2,
    step: 0.01,
  }),
  makeField({
    name: "animationMaxLandscapeScale",
    attr: "data-animation-max-landscape-scale",
    defaultValue: MASONRY_DEFAULTS.maxLandscapeScale,
    parse: "number",
    group: "tiles",
    label: "max landscape scale",
    control: "range",
    min: 0.1,
    max: 3,
    step: 0.01,
  }),
  makeField({
    name: "animationMinPortraitScale",
    attr: "data-animation-min-portrait-scale",
    defaultValue: MASONRY_DEFAULTS.minPortraitScale,
    parse: "number",
    group: "tiles",
    label: "min portrait scale",
    control: "range",
    min: 0.1,
    max: 4,
    step: 0.01,
  }),
  makeField({
    name: "animationMaxPortraitScale",
    attr: "data-animation-max-portrait-scale",
    defaultValue: MASONRY_DEFAULTS.maxPortraitScale,
    parse: "number",
    group: "tiles",
    label: "max portrait scale",
    control: "range",
    min: 0.1,
    max: 6,
    step: 0.01,
  }),
  makeField({
    name: "animationSquareScale",
    attr: "data-animation-square-scale",
    defaultValue: MASONRY_DEFAULTS.squareScale,
    parse: "number",
    group: "tiles",
    label: "square scale",
    control: "range",
    min: 0.1,
    max: 4,
    step: 0.01,
  }),
];

export const MASONRY_COMPONENT_PRESETS = MASONRY_PRESETS;

export function buildMasonryOptions(values) {
  const topSize = values.animationFadeTopSize;
  const bottomSize = values.animationFadeBottomSize;

  return {
    columnCount: values.animationColumnCount,
    preferredColumnWidth: Math.max(1, values.animationPreferredColumnWidth),
    minColumnWidth: Math.max(1, values.animationMinColumnWidth),
    maxColumnWidth: Math.max(values.animationMinColumnWidth, values.animationMaxColumnWidth),
    maxColumnCount: Math.max(1, Math.floor(values.animationMaxColumnCount)),
    columnWeights: values.animationColumnWeights,
    gap: Math.max(0, values.animationGap),
    columnGap: values.animationColumnGap,
    rowGap: values.animationRowGap,
    radius: Math.max(0, values.animationRadius),
    padding: Math.max(0, values.animationPadding),
    speed: scaledSpeed(Math.abs(values.animationSpeed), values.animationDuration),
    columnSpeeds: scaledNumberList(values.animationColumnSpeeds, values.animationDuration),
    direction: values.animationDirection,
    fade: {
      enabled: values.animationFadeEnabled,
      size: Math.max(0, values.animationFadeSize),
      sizes: {
        ...(topSize == null ? {} : { top: topSize }),
        ...(bottomSize == null ? {} : { bottom: bottomSize }),
      },
      sides: {
        top: values.animationFadeTop,
        bottom: values.animationFadeBottom,
      },
    },
    preload: Math.max(0, values.animationPreload),
    minCycleRatio: Math.max(1, values.animationMinCycleRatio),
    maxClonePasses: Math.max(1, Math.floor(values.animationMaxClonePasses)),
    minTileHeight: Math.max(1, values.animationMinTileHeight),
    maxTileHeight: Math.max(values.animationMinTileHeight, values.animationMaxTileHeight),
    minLandscapeScale: values.animationMinLandscapeScale,
    maxLandscapeScale: Math.max(values.animationMinLandscapeScale, values.animationMaxLandscapeScale),
    minPortraitScale: values.animationMinPortraitScale,
    maxPortraitScale: Math.max(values.animationMinPortraitScale, values.animationMaxPortraitScale),
    squareScale: values.animationSquareScale,
    maxDpr: Math.max(1, values.animationMaxDpr),
    pausedColumns: values.animationPausedColumns,
    pauseOnReducedMotion: values.animationPauseOnReducedMotion,
    interaction: buildInteraction(values),
  };
}

export const mountMasonryComponent = (target, { items } = {}) => mountDataComponent(target, {
  mount: mountMasonry,
  items,
  fields: MASONRY_FIELDS,
  presets: MASONRY_COMPONENT_PRESETS,
  buildOptions: buildMasonryOptions,
});
