#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import {
  copyFile,
  mkdir,
  readFile,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import {
  closestVariant,
  collectCanonicalAssets,
  duplicateGroups,
  ensureInside,
  generatedAssetDirectory,
  generatedStableFilename,
  generatedUrl,
  generatedVariantFilename,
  mediaOrientation,
  ratioToken,
  recipeHash,
  selectImageWidths,
  sha256File,
  stableJson,
} from "./media-system-core.mjs";
import {
  IMAGE_RECIPE,
  MEDIA_PATHS,
  MEDIA_PIPELINE_VERSION,
} from "./media.config.mjs";

function parseArguments(argv) {
  const options = {
    root: process.cwd(),
    force: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];

    if (argument === "--root") options.root = argv[++index];
    else if (argument === "--force") options.force = true;
    else throw new Error(`Unknown argument: ${argument}`);
  }

  options.root = path.resolve(options.root);
  return options;
}

async function readJson(filename, fallback) {
  try {
    return JSON.parse(await readFile(filename, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return fallback;
    throw error;
  }
}

function orientedDimensions(metadata) {
  const orientation = metadata.orientation ?? 1;
  const swapsAxes = [5, 6, 7, 8].includes(orientation);

  return {
    width: swapsAxes ? metadata.height : metadata.width,
    height: swapsAxes ? metadata.width : metadata.height,
  };
}

function imageQuality(width) {
  if (width <= IMAGE_RECIPE.fallbackTarget) {
    return IMAGE_RECIPE.quality.fallback;
  }

  if (width >= IMAGE_RECIPE.defaultTarget) {
    return IMAGE_RECIPE.quality.large;
  }

  return IMAGE_RECIPE.quality.regular;
}

function manifestModule(manifest) {
  return `// Generated by tools/media/prepare-media.mjs. Do not edit.\n` +
    `export const MEDIA_MANIFEST = Object.freeze(${JSON.stringify(manifest.entries, null, 2)});\n` +
    `export default MEDIA_MANIFEST;\n`;
}

function probeVideo(filename) {
  const result = spawnSync(
    "ffprobe",
    [
      "-v",
      "error",
      "-select_streams",
      "v:0",
      "-show_entries",
      "stream=width,height,duration",
      "-of",
      "json",
      filename,
    ],
    {
      encoding: "utf8",
      windowsHide: true,
    },
  );

  if (result.error || result.status !== 0) {
    return {
      width: null,
      height: null,
      duration: null,
      available: false,
    };
  }

  const parsed = JSON.parse(result.stdout || "{}");
  const stream = parsed.streams?.[0] ?? {};

  return {
    width: Number(stream.width) || null,
    height: Number(stream.height) || null,
    duration: Number(stream.duration) || null,
    available: true,
  };
}

async function removeManagedOutputs(projectRoot, outputPaths) {
  const generatedRoot = path.resolve(projectRoot, "public/media/generated");

  for (const output of outputPaths ?? []) {
    const absolute = ensureInside(
      generatedRoot,
      path.resolve(projectRoot, output),
    );

    await rm(absolute, { force: true });
  }
}

async function outputsExist(projectRoot, outputs) {
  if (!Array.isArray(outputs) || outputs.length === 0) return false;
  return outputs.every((output) =>
    existsSync(path.resolve(projectRoot, output)),
  );
}

function outputRelative(projectRoot, absolute) {
  return path.relative(projectRoot, absolute).replaceAll("\\", "/");
}

async function prepareImage({
  projectRoot,
  asset,
  sourceHash,
  previous,
}) {
  const image = sharp(asset.absolute, { failOn: "warning" });
  const metadata = await image.metadata();
  const dimensions = orientedDimensions(metadata);

  if (!dimensions.width || !dimensions.height) {
    throw new Error(`Could not read image dimensions: ${asset.absolute}`);
  }

  const actualRatio = ratioToken(dimensions.width, dimensions.height);

  if (actualRatio !== asset.ratio) {
    throw new Error(
      `Ratio token mismatch for ${asset.relativePath}: filename=${asset.ratio}, actual=${actualRatio} (${dimensions.width}x${dimensions.height})`,
    );
  }

  const directory = generatedAssetDirectory(projectRoot, asset);
  await mkdir(directory, { recursive: true });

  const widths = selectImageWidths(dimensions.width);
  const variants = [];

  for (const width of widths) {
    const filename = generatedVariantFilename(asset, width, sourceHash);
    const absolute = path.join(directory, filename);
    const output = await sharp(asset.absolute, { failOn: "warning" })
      .rotate()
      .resize({
        width,
        withoutEnlargement: IMAGE_RECIPE.withoutEnlargement,
      })
      .webp({
        quality: imageQuality(width),
        effort: IMAGE_RECIPE.effort,
      })
      .toFile(absolute);

    variants.push({
      src: generatedUrl(asset, filename),
      width: output.width,
      height: output.height,
      bytes: output.size,
      path: outputRelative(projectRoot, absolute),
    });
  }

  variants.sort((left, right) => left.width - right.width);

  const fallback = closestVariant(
    variants,
    IMAGE_RECIPE.fallbackTarget,
    "nearest",
  );
  const thumbnail = closestVariant(
    variants,
    IMAGE_RECIPE.thumbnailTarget,
    "at-least",
  );
  const defaultVariant = closestVariant(
    variants,
    IMAGE_RECIPE.defaultTarget,
    "at-least",
  );
  const fullscreen = variants.at(-1);
  const stableFilename = generatedStableFilename(asset);
  const stableAbsolute = path.join(directory, stableFilename);
  const stableTemporary = `${stableAbsolute}.tmp-${process.pid}`;

  await copyFile(
    path.resolve(projectRoot, defaultVariant.path),
    stableTemporary,
  );
  await rm(stableAbsolute, { force: true });
  await rename(stableTemporary, stableAbsolute);

  const stable = {
    src: generatedUrl(asset, stableFilename),
    width: defaultVariant.width,
    height: defaultVariant.height,
    path: outputRelative(projectRoot, stableAbsolute),
  };

  const entry = {
    id: asset.id,
    type: "image",
    ratio: actualRatio,
    orientation: mediaOrientation(dimensions.width, dimensions.height),
    width: dimensions.width,
    height: dimensions.height,
    source: `${MEDIA_PATHS.sources}/${asset.relativePath}`,
    sourceHash,
    default: {
      src: stable.src,
      width: stable.width,
      height: stable.height,
    },
    fallback: {
      src: fallback.src,
      width: fallback.width,
      height: fallback.height,
    },
    thumbnail: {
      src: thumbnail.src,
      width: thumbnail.width,
      height: thumbnail.height,
    },
    fullscreen: {
      src: fullscreen.src,
      width: fullscreen.width,
      height: fullscreen.height,
    },
    srcset: variants.map(({ src, width, height }) => ({
      src,
      width,
      height,
    })),
    content: {
      alt: "",
      caption: "",
      description: "",
      credit: "",
    },
  };

  const outputs = [
    ...variants.map((variant) => variant.path),
    stable.path,
  ];
  const outputSet = new Set(outputs);

  await removeManagedOutputs(
    projectRoot,
    (previous?.outputs ?? []).filter((output) => !outputSet.has(output)),
  );

  return {
    entry,
    outputs,
  };
}

async function prepareVideo({
  projectRoot,
  asset,
  sourceHash,
  previous,
}) {
  const directory = generatedAssetDirectory(projectRoot, asset);
  await mkdir(directory, { recursive: true });

  const short = sourceHash.slice(0, 8);
  const hashedFilename = `${asset.stem}--source-${short}${asset.extension}`;
  const stableFilename = generatedStableFilename(asset);
  const hashedAbsolute = path.join(directory, hashedFilename);
  const stableAbsolute = path.join(directory, stableFilename);

  const stableTemporary = `${stableAbsolute}.tmp-${process.pid}`;

  await copyFile(asset.absolute, hashedAbsolute);
  await copyFile(asset.absolute, stableTemporary);
  await rm(stableAbsolute, { force: true });
  await rename(stableTemporary, stableAbsolute);

  const probe = probeVideo(asset.absolute);
  const tokenParts = asset.ratio.split("x").map(Number);
  const width = probe.width;
  const height = probe.height;
  const actualRatio = width && height
    ? ratioToken(width, height)
    : asset.ratio;

  if (width && height && actualRatio !== asset.ratio) {
    throw new Error(
      `Ratio token mismatch for ${asset.relativePath}: filename=${asset.ratio}, actual=${actualRatio} (${width}x${height})`,
    );
  }

  const entry = {
    id: asset.id,
    type: "video",
    ratio: actualRatio,
    orientation: width && height
      ? mediaOrientation(width, height)
      : tokenParts[0] === tokenParts[1]
        ? "square"
        : tokenParts[0] > tokenParts[1]
          ? "landscape"
          : "portrait",
    width,
    height,
    duration: probe.duration,
    source: `${MEDIA_PATHS.sources}/${asset.relativePath}`,
    sourceHash,
    default: {
      src: generatedUrl(asset, stableFilename),
      width,
      height,
      type: asset.extension.slice(1),
    },
    fullscreen: {
      src: generatedUrl(asset, hashedFilename),
      width,
      height,
      type: asset.extension.slice(1),
    },
    poster: null,
    thumbnail: null,
    fallback: null,
    sources: [
      {
        src: generatedUrl(asset, hashedFilename),
        type: asset.extension.slice(1),
      },
    ],
    content: {
      alt: "",
      caption: "",
      description: "",
      credit: "",
    },
  };

  const outputs = [
    outputRelative(projectRoot, hashedAbsolute),
    outputRelative(projectRoot, stableAbsolute),
  ];
  const outputSet = new Set(outputs);

  await removeManagedOutputs(
    projectRoot,
    (previous?.outputs ?? []).filter((output) => !outputSet.has(output)),
  );

  return {
    entry,
    outputs,
  };
}

async function main() {
  const options = parseArguments(process.argv.slice(2));
  const cachePath = path.resolve(options.root, MEDIA_PATHS.cache);
  const manifestJsonPath = path.resolve(
    options.root,
    MEDIA_PATHS.manifestJson,
  );
  const manifestModulePath = path.resolve(
    options.root,
    MEDIA_PATHS.manifestModule,
  );
  const reportsDirectory = path.resolve(
    options.root,
    MEDIA_PATHS.reports,
  );
  const currentRecipeHash = recipeHash();
  const previousState = await readJson(cachePath, {
    version: MEDIA_PIPELINE_VERSION,
    recipeHash: currentRecipeHash,
    assets: {},
  });
  const assets = await collectCanonicalAssets(options.root);

  if (!assets.length) {
    throw new Error(
      `No canonical media found in ${path.resolve(options.root, MEDIA_PATHS.sources)}. Run media:bootstrap first.`,
    );
  }

  const nextState = {
    version: MEDIA_PIPELINE_VERSION,
    recipeHash: currentRecipeHash,
    assets: {},
  };
  const entries = {};
  let preparedCount = 0;
  let reusedCount = 0;

  for (const asset of assets) {
    const previous = previousState.assets?.[asset.relativePath] ?? null;
    const statMatches = previous &&
      previous.size === asset.size &&
      previous.mtimeMs === asset.mtimeMs &&
      previous.recipeHash === currentRecipeHash;
    const canReuse = !options.force &&
      statMatches &&
      await outputsExist(options.root, previous.outputs);

    if (canReuse) {
      entries[asset.id] = previous.entry;
      nextState.assets[asset.relativePath] = previous;
      reusedCount += 1;
      continue;
    }

    const sourceHash = await sha256File(asset.absolute);
    const contentMatches = !options.force &&
      previous?.sourceHash === sourceHash &&
      previous.recipeHash === currentRecipeHash &&
      await outputsExist(options.root, previous.outputs);

    if (contentMatches) {
      const reused = {
        ...previous,
        size: asset.size,
        mtimeMs: asset.mtimeMs,
      };

      entries[asset.id] = reused.entry;
      nextState.assets[asset.relativePath] = reused;
      reusedCount += 1;
      continue;
    }

    const result = asset.type === "image"
      ? await prepareImage({
          projectRoot: options.root,
          asset,
          sourceHash,
          previous,
        })
      : await prepareVideo({
          projectRoot: options.root,
          asset,
          sourceHash,
          previous,
        });

    const stateEntry = {
      id: asset.id,
      source: asset.relativePath,
      sourceHash,
      size: asset.size,
      mtimeMs: asset.mtimeMs,
      recipeHash: currentRecipeHash,
      outputs: result.outputs,
      entry: result.entry,
    };

    entries[asset.id] = result.entry;
    nextState.assets[asset.relativePath] = stateEntry;
    preparedCount += 1;
  }

  const currentSources = new Set(
    assets.map((asset) => asset.relativePath),
  );

  for (const [source, previous] of Object.entries(previousState.assets ?? {})) {
    if (currentSources.has(source)) continue;
    await removeManagedOutputs(options.root, previous.outputs);
  }

  const sortedEntries = Object.fromEntries(
    Object.entries(entries).sort(([left], [right]) =>
      left.localeCompare(right, "en"),
    ),
  );
  const manifest = {
    version: MEDIA_PIPELINE_VERSION,
    recipeHash: currentRecipeHash,
    generatedAt: new Date().toISOString(),
    entries: sortedEntries,
  };
  const duplicates = duplicateGroups(Object.values(sortedEntries));

  await mkdir(path.dirname(cachePath), { recursive: true });
  await mkdir(path.dirname(manifestJsonPath), { recursive: true });
  await mkdir(reportsDirectory, { recursive: true });

  await writeFile(cachePath, stableJson(nextState), "utf8");
  await writeFile(manifestJsonPath, stableJson(manifest), "utf8");
  await writeFile(
    manifestModulePath,
    manifestModule(manifest),
    "utf8",
  );
  await writeFile(
    path.join(reportsDirectory, "duplicates.json"),
    stableJson({
      version: 1,
      generatedAt: manifest.generatedAt,
      groups: duplicates,
    }),
    "utf8",
  );

  console.log(`Media prepared: ${preparedCount}`);
  console.log(`Media reused: ${reusedCount}`);
  console.log(`Manifest entries: ${Object.keys(sortedEntries).length}`);
  console.log(`Exact duplicate groups: ${duplicates.length}`);
}

main().catch((error) => {
  console.error(error.stack || error.message || error);
  process.exitCode = 1;
});
