import { PageFlip } from "page-flip";
const reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)");
const touchPointer=window.matchMedia("(hover: none), (pointer: coarse)");
function initCaptions(root,signal){
  const closeAll=(except=null)=>root.querySelectorAll('figure[data-caption-open="true"]').forEach(f=>{if(f!==except)f.removeAttribute("data-caption-open")});
  root.addEventListener("click",e=>{if(!touchPointer.matches)return;const surface=e.target.closest("[data-media-caption-surface]");if(!surface||!root.contains(surface)){closeAll();return}const figure=surface.closest("figure[data-sensetique-hover-caption]");if(!figure){closeAll();return}const willOpen=figure.getAttribute("data-caption-open")!=="true";closeAll(figure);if(willOpen)figure.setAttribute("data-caption-open","true");else figure.removeAttribute("data-caption-open")},{signal});
  root.addEventListener("keydown",e=>{const surface=e.target.closest("[data-media-caption-surface]");if(!surface||!root.contains(surface))return;const figure=surface.closest("figure[data-sensetique-hover-caption]");if(!figure)return;if(e.key==="Escape"){figure.removeAttribute("data-caption-open");surface.blur();return}if(touchPointer.matches&&(e.key==="Enter"||e.key===" ")){e.preventDefault();const open=figure.getAttribute("data-caption-open")==="true";closeAll(figure);if(open)figure.removeAttribute("data-caption-open");else figure.setAttribute("data-caption-open","true")}}, {signal});
}
function initCrossfades(root,signal,timers){
  root.querySelectorAll("[data-crossfade-slider]").forEach(slider=>{const slides=[...slider.querySelectorAll(":scope > [data-slider-slide]")];if(slides.length<2)return;const owner=slider.closest("figure, .sensetique-crossfade-media")||slider;const prev=owner.querySelector("[data-slider-prev]");const next=owner.querySelector("[data-slider-next]");const count=owner.querySelector("[data-slider-count]");const caption=owner.querySelector("[data-slider-caption]");const sequence=owner.querySelector("[data-slider-sequence-index]");const interval=Number.parseInt(slider.dataset.sliderInterval||"4200",10);let index=Math.max(0,slides.findIndex(s=>s.hasAttribute("data-active")));let timer=0;
    const stop=()=>{if(!timer)return;clearInterval(timer);timers.delete(timer);timer=0};
    const render=()=>{slides.forEach((s,i)=>i===index?s.setAttribute("data-active",""):s.removeAttribute("data-active"));if(count)count.textContent=`${String(index+1).padStart(2,"0")} / ${String(slides.length).padStart(2,"0")}`;const active=slides[index];if(caption)caption.textContent=active.dataset.caption||active.alt||"";if(sequence&&active.dataset.mediaSequence)sequence.textContent=active.dataset.mediaSequence;slider.dispatchEvent(new CustomEvent("sensetique:slidechange",{bubbles:true,detail:{slider,activeSlide:active,index}}))};
    const move=d=>{index=(index+d+slides.length)%slides.length;render()};
    const start=()=>{stop();if(reduceMotion.matches)return;timer=setInterval(()=>move(1),interval);timers.add(timer)};
    prev?.addEventListener("click",()=>{move(-1);start()},{signal});next?.addEventListener("click",()=>{move(1);start()},{signal});owner.addEventListener("focusin",stop,{signal});owner.addEventListener("focusout",start,{signal});reduceMotion.addEventListener("change",start,{signal});render();start();
  });
}
function initFlipbook(root,signal,disposers){const section=root.querySelector("[data-sensetique-flipbook-section]");if(!section)return;const book=section.querySelector("[data-sensetique-flipbook]");const pages=book?.querySelectorAll(".sensetique-flipbook__page");const prev=section.querySelector(".sensetique-flipbook-prev");const next=section.querySelector(".sensetique-flipbook-next");const count=section.querySelector(".sensetique-flipbook-count");if(!book||!pages?.length||!prev||!next||!count)return;const pf=new PageFlip(book,{width:550,height:778,size:"stretch",minWidth:260,maxWidth:580,minHeight:368,maxHeight:820,drawShadow:true,flippingTime:1180,usePortrait:false,startZIndex:0,startPage:0,autoSize:true,maxShadowOpacity:.18,showCover:false,mobileScrollSupport:false,swipeDistance:8,clickEventForward:false,useMouseEvents:true,showPageCorners:true,disableFlipByClick:false});pf.loadFromHTML(pages);const update=()=>{const current=pf.getCurrentPageIndex();count.textContent=`${String(Math.floor(current/2)+1).padStart(2,"0")} / ${String(Math.ceil(pf.getPageCount()/2)).padStart(2,"0")}`;prev.disabled=current<=0;next.disabled=current>=pf.getPageCount()-2};pf.on("init",update);pf.on("flip",update);prev.addEventListener("click",()=>pf.flipPrev("bottom"),{signal});next.addEventListener("click",()=>pf.flipNext("bottom"),{signal});update();disposers.push(()=>pf.destroy?.())}
function initStudioRows(root,signal,disposers){const studio=root.querySelector(".sensetique-studio-grid-composition");if(!studio)return()=>{};const rows=[...studio.querySelectorAll(":scope > .sensetique-studio-grid-composition__row")];const ratio=item=>{const media=item.querySelector("img[data-media-id],video[data-media-id]");if(!media)return 1;if(media instanceof HTMLImageElement){const w=media.naturalWidth||Number(media.getAttribute("width"))||1;const h=media.naturalHeight||Number(media.getAttribute("height"))||1;return w>0&&h>0?w/h:1}const w=media.videoWidth||Number(media.getAttribute("width"))||1;const h=media.videoHeight||Number(media.getAttribute("height"))||1;return w>0&&h>0?w/h:1};let frame=0;const relayout=()=>{frame=0;if(matchMedia("(width <= 47.999rem)").matches){rows.forEach(row=>{row.style.removeProperty("--studio-row-height");row.querySelectorAll(":scope > .sensetique-studio-grid-composition__item").forEach(item=>item.style.removeProperty("--studio-item-width"))});return}rows.forEach(row=>{const items=[...row.querySelectorAll(":scope > .sensetique-studio-grid-composition__item:not([hidden])")];if(!items.length)return;const rs=getComputedStyle(row);const gap=parseFloat(rs.columnGap||rs.gap)||0;const available=row.clientWidth-gap*Math.max(0,items.length-1);if(available<=0)return;const ratios=items.map(ratio);const h=available/(ratios.reduce((a,b)=>a+b,0)||1);row.style.setProperty("--studio-row-height",`${h}px`);items.forEach((item,i)=>item.style.setProperty("--studio-item-width",`${h*ratios[i]}px`))})};const schedule=()=>{if(!frame)frame=requestAnimationFrame(relayout)};studio.querySelectorAll("img[data-media-id]").forEach(img=>{if(!(img.complete&&img.naturalWidth>0))img.addEventListener("load",schedule,{passive:true,signal})});studio.querySelectorAll("video[data-media-id]").forEach(v=>v.addEventListener("loadedmetadata",schedule,{passive:true,signal}));const ro=typeof ResizeObserver==="function"?new ResizeObserver(schedule):null;ro?.observe(studio);disposers.push(()=>ro?.disconnect());schedule();return schedule}
export function initSensetiqueSection(root=document.querySelector(".cv-item--sensetique")){if(!(root instanceof HTMLElement))throw new Error("Sensetique root was not found.");const controller=new AbortController();const signal=controller.signal;const timers=new Set();const disposers=[];initCaptions(root,signal);initCrossfades(root,signal,timers);initFlipbook(root,signal,disposers);const refreshStudio=initStudioRows(root,signal,disposers);return{root,refresh(){refreshStudio?.()},destroy(){controller.abort();timers.forEach(t=>clearInterval(t));timers.clear();disposers.forEach(fn=>fn());root.querySelectorAll('[data-caption-open="true"]').forEach(f=>f.removeAttribute("data-caption-open"))}}}
