export const BASELINE_VIEWPORTS = [
  { name: "desktop-1920x1080", width: 1920, height: 1080 },
  { name: "desktop-1600x1000", width: 1600, height: 1000 },
  { name: "desktop-1440x900", width: 1440, height: 900 },
  { name: "desktop-1280x800", width: 1280, height: 800 },
  { name: "tablet-1024x768", width: 1024, height: 768 },
  { name: "tablet-768x1024", width: 768, height: 1024 },
  { name: "mobile-430x932", width: 430, height: 932 },
  { name: "mobile-390x844", width: 390, height: 844 },
  { name: "mobile-375x812", width: 375, height: 812 },
  { name: "mobile-360x800", width: 360, height: 800 },
];

export const BASELINE_SECTION_IDS = [
  "hero",
  "jestei-cover",
  "jestei-results",
  "jestei-words",
  "jestei-logo",
  "jestei-color",
  "jestei-audience-map",
  "jestei-tariffs",
  "jestei-filter",
  "jestei-event-nav",
  "jestei-interface",
  "jestei-graphics",
  "styx-cover",
  "styx-graphics",
  "styx-packaging",
  "styx-communications",
  "styx-print",
  "styx-photo-art",
  "styx-scanography",
  "shootings",
  "pet-projects",
  "resume",
  "contacts",
];

export const COMPUTED_STYLE_PROPERTIES = [
  "display",
  "visibility",
  "opacity",
  "position",
  "boxSizing",
  "inlineSize",
  "blockSize",
  "width",
  "height",
  "maxWidth",
  "minHeight",
  "marginTop",
  "marginRight",
  "marginBottom",
  "marginLeft",
  "paddingTop",
  "paddingRight",
  "paddingBottom",
  "paddingLeft",
  "overflowX",
  "overflowY",
  "fontFamily",
  "fontSize",
  "fontWeight",
  "lineHeight",
  "letterSpacing",
  "textAlign",
  "color",
  "backgroundColor",
  "borderRadius",
  "gridTemplateColumns",
  "gap",
];

export const BASELINE_INTERACTION_SELECTORS = {
  lightboxTrigger: "[data-lightbox-item], [data-lightbox-video], a[data-section-media-item][href]",
  lightboxRoot: ".lightbox.is-open",
  horizontalScroll: '[data-animation="horizontal"]',
  policyBook: "[data-policy-book]",
  policyNext: "[data-policy-next]",
  playlistFilterRoot: "[data-filter-fullscreen-root]",
  playlistFilterButton: "[data-filter-fullscreen]",
  petProjectButton: ".pet-projects-bento__open",
  petProjectModal: "#pet-project-modal",
  navTrigger: "[data-nav-trigger]",
  navMenu: "[data-nav-menu]",
};

export const ALLOWED_CONSOLE_PATTERNS = [
  /WebGL/i,
  /THREE\.WebGLRenderer/i,
  /GL_INVALID/i,
  /GPU stall/i,
  /favicon/i,
  /ResizeObserver loop/i,
];
