import { mountArc, ARC_DEFAULTS } from "./index.js";
import {
  mountDataComponent,
  COMMON_PRESETS,
  buildInteraction,
  createSharedFields,
  makeField,
  scaledSpeed,
} from "../../runtime/master-runtime.js";

const PRESET_ORDER = [
  "scroll-driven",
  "autoplay",
  "scroll-slowdown",
  "center-slowdown",
];

export const ARC_FIELDS = [
  ...createSharedFields({
    presetOptions: PRESET_ORDER,
    defaultPreset: "autoplay",
    cycleMs: 20000,
  }),
  makeField({
    name: "animationDirection",
    attr: "data-animation-direction",
    defaultValue: "auto",
    group: "motion",
    label: "direction",
    control: "select",
    options: ["auto", "clockwise", "counter-clockwise"],
  }),
  makeField({
    name: "animationSpeed",
    attr: "data-animation-speed",
    defaultValue: ARC_DEFAULTS.speed,
    parse: "number",
    group: "motion",
    label: "base speed",
    control: "number",
    min: 0,
    max: 0.01,
    step: 0.00001,
  }),
  makeField({
    name: "animationSlots",
    attr: "data-animation-slots",
    defaultValue: ARC_DEFAULTS.slots,
    parse: "integer",
    group: "geometry",
    label: "slots",
    control: "range",
    min: 1,
    max: 32,
    step: 1,
  }),
  makeField({
    name: "animationRadiusScale",
    attr: "data-animation-radius-scale",
    defaultValue: ARC_DEFAULTS.radiusScale,
    parse: "number",
    group: "geometry",
    label: "arc radius scale",
    control: "range",
    min: 0.1,
    max: 1.5,
    step: 0.01,
  }),
  makeField({
    name: "animationCardBaseScale",
    attr: "data-animation-card-base-scale",
    defaultValue: ARC_DEFAULTS.cardBaseScale,
    parse: "number",
    group: "cards",
    label: "card base scale",
    control: "range",
    min: 0.02,
    max: 0.6,
    step: 0.01,
  }),
  makeField({
    name: "animationCardMinScale",
    attr: "data-animation-card-min-scale",
    defaultValue: ARC_DEFAULTS.cardMinScale,
    parse: "number",
    group: "cards",
    label: "card min scale",
    control: "range",
    min: 0,
    max: 1,
    step: 0.01,
  }),
  makeField({
    name: "animationCardMaxBonus",
    attr: "data-animation-card-max-bonus",
    defaultValue: ARC_DEFAULTS.cardMaxBonus,
    parse: "number",
    group: "cards",
    label: "card max bonus",
    control: "range",
    min: 0,
    max: 3,
    step: 0.01,
  }),
  makeField({
    name: "animationCardFocusPower",
    attr: "data-animation-card-focus-power",
    defaultValue: ARC_DEFAULTS.cardFocusPower,
    parse: "number",
    group: "cards",
    label: "card focus power",
    control: "range",
    min: 0.1,
    max: 6,
    step: 0.1,
  }),
  makeField({
    name: "animationCardRadiusScale",
    attr: "data-animation-card-radius-scale",
    defaultValue: ARC_DEFAULTS.cardRadiusScale,
    parse: "number",
    group: "cards",
    label: "card radius scale",
    control: "range",
    min: 0,
    max: 0.5,
    step: 0.01,
  }),
  makeField({
    name: "animationTitleScale",
    attr: "data-animation-title-scale",
    defaultValue: ARC_DEFAULTS.titleScale,
    parse: "number",
    group: "title",
    label: "title scale",
    control: "range",
    min: 0,
    max: 0.3,
    step: 0.005,
  }),
  makeField({
    name: "animationTitleOffsetY",
    attr: "data-animation-title-offset-y",
    defaultValue: ARC_DEFAULTS.titleOffsetY,
    parse: "number",
    group: "title",
    label: "title offset y",
    control: "range",
    min: -1,
    max: 2,
    step: 0.01,
  }),
  makeField({
    name: "animationTitleMaxWidth",
    attr: "data-animation-title-max-width",
    defaultValue: ARC_DEFAULTS.titleMaxWidth,
    parse: "number",
    group: "title",
    label: "title max width",
    control: "range",
    min: 0.5,
    max: 4,
    step: 0.05,
  }),
  makeField({
    name: "animationEdgeFadeStart",
    attr: "data-animation-edge-fade-start",
    defaultValue: ARC_DEFAULTS.edgeFadeStart,
    parse: "number",
    group: "effects",
    label: "edge fade start",
    control: "range",
    min: 0,
    max: 1,
    step: 0.01,
  }),
  makeField({
    name: "animationEdgeFadePower",
    attr: "data-animation-edge-fade-power",
    defaultValue: ARC_DEFAULTS.edgeFadePower,
    parse: "number",
    group: "effects",
    label: "edge fade power",
    control: "range",
    min: 0.1,
    max: 16,
    step: 0.1,
  }),
];

export const ARC_PRESETS = COMMON_PRESETS;

export function buildArcOptions(values) {
  const direction = values.animationDirection === "counter-clockwise" ? -1 : 1;
  return {
    slots: Math.max(1, Math.floor(values.animationSlots)),
    speed: scaledSpeed(Math.abs(values.animationSpeed), values.animationDuration) * direction,
    radiusScale: values.animationRadiusScale,
    cardBaseScale: values.animationCardBaseScale,
    cardMinScale: values.animationCardMinScale,
    cardMaxBonus: values.animationCardMaxBonus,
    cardFocusPower: values.animationCardFocusPower,
    titleScale: values.animationTitleScale,
    titleOffsetY: values.animationTitleOffsetY,
    titleMaxWidth: values.animationTitleMaxWidth,
    edgeFadeStart: values.animationEdgeFadeStart,
    edgeFadePower: values.animationEdgeFadePower,
    cardRadiusScale: values.animationCardRadiusScale,
    maxDpr: Math.max(1, values.animationMaxDpr),
    pauseOnReducedMotion: values.animationPauseOnReducedMotion,
    interaction: buildInteraction(values),
  };
}

export const mountArcComponent = (target, { items } = {}) => mountDataComponent(target, {
  mount: mountArc,
  items,
  fields: ARC_FIELDS,
  presets: ARC_PRESETS,
  buildOptions: buildArcOptions,
});
